name: personal_journal
description: A Personal Journal app for UTS
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  intl: ^0.18.0
  uuid: ^3.0.7
  google_fonts: ^4.0.3
  path: ^1.9.1
  video_player: ^2.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
dev_dependencies:
  flutter_lints: ^6.0.0
